version: '3.1'

services:
  # ref: https://raw.githubusercontent.com/verdaccio/verdaccio/master/docker-examples/v6/docker-local-storage-volume/conf/config.yaml
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'verdaccio'
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_PROTOCOL=https
    ports:
      - '4873:4873'
    volumes:
      - './.verdaccio/storage:/verdaccio/storage'
      - './.verdaccio/config:/verdaccio/conf'
      - './.verdaccio/plugins:/verdaccio/plugins'

networks:
  node-network:
    driver: bridge
