# References:
# - https://github.com/shingtoli/verdaccio-compose-local-bridge/blob/master/conf/config.yaml
# - https://raw.githubusercontent.com/andru255/verdaccio-server/master/conf/config.yaml
# - https://community.hetzner.com/tutorials/verdaccio-secure-fedora-server

#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage

listen: 
  - https://registry.dev:4873
  - https://0.0.0.0:4873

# ref: https://verdaccio.org/docs/ssl
https:
    key:  /verdaccio/conf/registry.dev+6-key.pem
    cert: /verdaccio/conf/registry.dev+6.pem
#    ca:   /verdaccio/conf/rootCA.pem

auth:
  htpasswd:
    file: ./htpasswd
    algorithm: bcrypt
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

web:
  enable: true
  login: false

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  yarn:
    url: https://registry.yarnpkg.com
    
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings, levels: fatal, error, warn, http, info, debug, trace
log: { type: stdout, format: pretty, level: http }
#log: {type: file, path: verdaccio.log, level: info}
