# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        packages: [be-configs, be-eslint-plugin]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies and run tests
        run: |
          cd ${{ matrix.packages }}
          ls -la .
          npm install
          npm test

  publish-gpr:
    needs: build
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        packages: [be-configs]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies and publish the package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cd ${{ matrix.packages }}
          npm install
          npm publish
