# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        packages: [be-configs]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd ${{ matrix.packages }}
      - run: npm install # use npm ci only if available lock files
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        packages: [be-configs]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: cd ${{ matrix.packages }}
      - run: npm install # use npm ci only if available lock files
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
