# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [ created ]

strategy: &buildMatrix
  matrix:
    packages:
      - be-configs
      - be-eslint-plugin
      - be-eslint-config
      - be-genproto
      - be-types
      - be-scaffold
      - be-pkg-test
      - be-pkg-i18n
      - be-pkg-errors
      - be-pkg-validators
      - be-pkg-utils
      - be-pkg-healthcheck
      - be-diia-logger
      - be-pkg-http
      - be-pkg-env
      - be-pkg-crypto
      - be-pkg-redis
      - be-pkg-db
      - be-pkg-cms
      - be-pkg-analytics
      - be-diia-metrics
      - be-diia-queue
      - be-pkg-providers
      - be-diia-app

jobs:
  build:
    runs-on: macos-latest
    <<: *buildMatrix
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'
      - name: Install dependencies and run tests
        run: |
          [ ! -d ${{ matrix.packages }} ] && echo "Directory ${{ matrix.packages }} does not exist" && exit 0 
          cd ${{ matrix.packages }}
          npm install
          npm test

  publish-gpr:
    needs: build
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        packages: [ be-configs ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'
      - name: Install dependencies and publish the package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cd ${{ matrix.packages }}
          npm install
          npm publish
